version: '3'

services:
  e2e_tests:
    image: ubuntu:14.04
    depends_on:
      - web
    command: 'nc -vz web 8080'
  web:
    image: ubuntu:14.04
    command: >
      /bin/bash -c "
        sleep 5;
        nc -lk 0.0.0.0 8080;
      "
  mongo:
    image: mongo:4.2-bionic
    container_name: ca-mongo
    restart: always
    logging:
      options:
          max-file: "5"
          max-size: "10m"
    volumes:
      - ./db:/data/db
  idxMongo:
    image: mongo:4.2-bionic
    container_name: ca-idx
    links:
      - mongo
    volumes:
      - ./config:/config
    command: bash /config/run_idx.sh
    logging:
      options:
          max-file: "5"
          max-size: "10m"
    depends_on:
      - mongo
  back:
    build:
      context: "https://github.com/camicroscope/caracal.git#fda/htt"
      args:
        viewer: "fda/htt"
        fork: "camicroscope"
    depends_on:
      - "mongo"
    ports:
      - "4010:4010"
    container_name: ca-back
    restart: always
    logging:
      options:
          max-file: "5"
          max-size: "10m"
    volumes:
      - ./images/:/images/
      - ./config/login.html:/src/static/login.html
      - ./jwt_keys/:/src/keys/
      - ./config/routes.json:/src/routes.json
      - ./config/contentSecurityPolicy.json:/src/contentSecurityPolicy.json
    environment:
      JWK_URL: "https://www.googleapis.com/oauth2/v3/certs"
      IIP_PATH: "http://ca-iip:8080/fcgi-bin/iipsrv.fcgi"
      MONGO_URI: "mongodb://ca-mongo"
      DISABLE_TF: "true"
      ALLOW_PUBLIC: "true"
      DISABLE_SEC: "true"
  iip:
    image: camicroscope/iipimage:version-3.8.4
    container_name: ca-iip
    logging:
      options:
          max-file: "5"
          max-size: "10m"
    restart: always
    volumes:
      - ./images/:/images/
  loader:
    build: "https://github.com/camicroscope/SlideLoader.git#v3.9.8"
    container_name: ca-load
    restart: always
    logging:
      options:
          max-file: "5"
          max-size: "10m"
    volumes:
      - ./images/:/images/
  start_dependencies:
    image: ubuntu:14.04
    depends_on:
      - web
    command: >
      /bin/bash -c "
        while ! nc -z web 8080;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
      "
